name: Publish

on:
  push:
    tags:
      - "*.*.*"



env:
  PROJECT_PATH: bis-file-formats.sln

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          dotnet build ${{ env.PROJECT_PATH }} -c Release -o "publish" --no-restore -p:PackageVersion=$VERSION
      
      - name: Add source
        run: dotnet nuget add source --username rvost --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rvost/index.json"
      
      - name: Puplish packages
        run: dotnet nuget push "publish/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
